GerenciadorDespecas/Models/Salario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GerenciadorDespecas.Models
{
    public class Salario
    {
        public int SalarioId { get; set; }
        [Required(ErrorMessage ="Campo Obrigatorio")]
        [Range(0,double.MaxValue, ErrorMessage ="Maximo de 50 caracteres")]
        public double Valor { get; set; }
        public int MesId { get; set; }
        public Meses Meses { get; set; }


    }
}

GerenciadorDespecas/Controllers/SalariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorDespecas.Models;

namespace GerenciadorDespecas.Controllers
{
    public class SalariosController : Controller
    {
        private readonly Contexto _context;

        public SalariosController(Contexto context)
        {
            _context = context;
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var contexto = _context.salarios.Include(s => s.Meses);
            return View(await contexto.ToListAsync());
        }


        [HttpPost]
        public async Task<IActionResult> Index(string txtProcurar)
        {
            if (!String.IsNullOrEmpty(txtProcurar))
            {
                return View(await _context.salarios.Include(x => x.Meses).Where(m => m.Meses.Nome.ToUpper().Contains(txtProcurar.ToUpper())).ToListAsync());
            }
            return View(_context.salarios.Include(s => s.Meses).ToListAsync());
        }

        // GET: Salarios/Create
        public IActionResult Create()
        {
            ViewData["MesId"] = new SelectList(_context.meses.Where(x => x.MesId != x.salario.MesId), "MesId", "Nome");
            return View();
        }

        // POST: Salarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalarioId,Valor,MesId")] Salario salario)
        {
            if (ModelState.IsValid)
            {
                TempData["Confimarcao"] = "Salario cadastrado com sucesso!!!";
                _context.Add(salario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.meses.Where(x => x.MesId != x.salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        // GET: Salarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var salario = await _context.salarios.FindAsync(id);
            if (salario == null)
            {
                return NotFound();
            }
            ViewData["MesId"] = new SelectList(_context.meses.Where(x => x.MesId == salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }

        // POST: Salarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalarioId,Valor,MesId")] Salario salario)
        {
            if (id != salario.SalarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                TempData["Confirmacao"] = "Salario Editado com sucesso!!!";
                try
                {
                    _context.Update(salario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalarioExists(salario.SalarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.meses.Where(x=>x.MesId == salario.MesId), "MesId", "Nome", salario.MesId);
            return View(salario);
        }


        // POST: Salarios/Delete/5
        [HttpPost]
        
        public async Task<IActionResult> Delete(int id)
        {
            TempData["Confirmacao"] = "Salario Excluido com sucesso!!";
            var salario = await _context.salarios.FindAsync(id);
            _context.salarios.Remove(salario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool SalarioExists(int id)
        {
            return _context.salarios.Any(e => e.SalarioId == id);
        }
    }
}

GerenciadorDespecas/Views/Salarios/Create.cshtml
@model GerenciadorDespecas.Models.Salario

@{
    ViewData["Title"] = "Novo Salario";
}

<div class="formulario">
    <h4>Salario</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" class="form rounded border">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MesId" class="control-label">Mês</label>
                    <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" />&nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorDespecas/Views/Salarios/Delete.cshtml
@model GerenciadorDespecas.Models.Salario

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Meses)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Meses.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SalarioId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GerenciadorDespecas/Views/Salarios/Edit.cshtml
@model GerenciadorDespecas.Models.Salario

@{
    ViewData["Title"] = "Atualizar Salario";
}
<div class="formulario">
    <h4>Salario</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" class="form rounded boder">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="SalarioId" />
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MesId" class="control-label">Mês</label>
                    <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                    <span asp-validation-for="MesId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-sucess btn-sm" />&nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorDespecas/Views/Salarios/Index.cshtml
@model IEnumerable<GerenciadorDespecas.Models.Salario>

@{
    ViewData["Title"] = "Salario Cadastrados";
}

<div class="tabela">
    <div class="container">
        <h6>Salario cadastados</h6>
        <p class="btnNovo">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm">Novo Salario</a>
        </p>

        @if (TempData["Confiracao"] != null)
        {
            <h6 class="alert alert-success">
                @TempData["Confircao"]
            </h6>
        }


        <form asp-action="Index" asp-controller="Salarios" method="post">
            <div class="form-group">
                <div class="input-group col-md-6">
                    <input class="form-control" name="txtProcurar" />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-dark"><i class="fas fa-search-plus"></i></button>
                    </div>
                </div>
            </div>
        </form>




        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Valor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Meses)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Meses.Nome)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.SalarioId" class="btn btn-outline-primary btn-sm">Editar</a> |
                            <a onclick="ExibirModal(@item.SalarioId)" class="btn btn-outline-danger btn-sm">Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir o salario ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function ExibirModal(id) {
          //  $(".nome")[0].innerHTML = nome;
            $(".modal").modal();
            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "Salarios/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>
}