GerenciadorDespecas/Models/Despesas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GerenciadorDespecas.Models
{
    public class Despesas
    {
        public int DespesaId { get; set; }
        public int MesId { get; set; }
        public Meses Meses { get; set; }
        public int TipoDespesaId { get; set; }
        [Required(ErrorMessage = "Campo Obrigatorio")]
        [Range(0, double.MaxValue, ErrorMessage = "Maximo de 50 caracteres")]
        public double Valor { get; set; }
        public TipoDespesas TipoDespesas { get; set; }
    }
}

GerenciadorDespecas/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorDespecas.Models;
using X.PagedList;
using GerenciadorDespecas.ViewModels;

namespace GerenciadorDespecas.Controllers
{
    public class DespesasController : Controller
    {
        private readonly Contexto _context;

        public DespesasController(Contexto context)
        {
            _context = context;
        }

        // GET: Despesas
        public async Task<IActionResult> Index(int? pagina)
        {
            const int itensPgina = 10;
            int numeroPagina = (pagina ?? 1);
            ViewData["Meses"] = new SelectList(_context.meses.Where(x => x.MesId == x.salario.MesId),"MesId","Nome");
            var contexto = _context.despesas.Include(d => d.Meses).Include(d => d.TipoDespesas).OrderBy(d => d.MesId);
            return View(await contexto.ToPagedListAsync(numeroPagina, itensPgina));
        }

       
        // GET: Despesas/Create
        public IActionResult Create()
        {
            TempData["Confirmacao"] = "Despesa Cadastrada com sucesso!";
            ViewData["MesId"] = new SelectList(_context.meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(_context.tipoDespesas, "TipoDespesaId", "Nome");
            return View();
        }

        // POST: Despesas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DespesaId,MesId,TipoDespesaId,Valor")] Despesas despesas)
        {
            if (ModelState.IsValid)
            {

                TempData["Confirmacao"] = "Despesa Cadastrada com sucesso";
                _context.Add(despesas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.meses, "MesId", "Nome", despesas.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.tipoDespesas, "TipoDespesaId", "Nome", despesas.TipoDespesaId);
            return View(despesas);
        }

        // GET: Despesas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var despesas = await _context.despesas.FindAsync(id);
            if (despesas == null)
            {
                return NotFound();
            }
            ViewData["MesId"] = new SelectList(_context.meses, "MesId", "Nome", despesas.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.tipoDespesas, "TipoDespesaId", "Nome", despesas.TipoDespesaId);
            return View(despesas);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DespesaId,MesId,TipoDespesaId,Valor")] Despesas despesas)
        {
            if (id != despesas.DespesaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                TempData["Confirmacao"] = "Despesa Editada com Sucesso";
                try
                {
                    _context.Update(despesas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DespesasExists(despesas.DespesaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MesId"] = new SelectList(_context.meses, "MesId", "Nome", despesas.MesId);
            ViewData["TipoDespesaId"] = new SelectList(_context.tipoDespesas, "TipoDespesaId", "Nome", despesas.TipoDespesaId);
            return View(despesas);
        }


        // POST: Despesas/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            TempData["Confirmacao"] = "Deletado com sucesso!!";
            var despesas = await _context.despesas.FindAsync(id);
            _context.despesas.Remove(despesas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DespesasExists(int id)
        {
            return _context.despesas.Any(e => e.DespesaId == id);
        }

        public JsonResult GastosTotaisMes(int mesId)
        {
            GastosTotaisViewModel gasto = new GastosTotaisViewModel();
            gasto.ValorTotalGasto = _context.despesas.Where(d => d.Meses.MesId == mesId).Sum(s => s.Valor);
            gasto.Salario = _context.salarios.Where(d => d.Meses.MesId == mesId).Select(s => s.Valor).FirstOrDefault();

            return Json(gasto);

        }

        public JsonResult GastosMes(int mesId)
        {
            var query = from despesas in _context.despesas
                        where despesas.Meses.MesId == mesId
                        group despesas by despesas.TipoDespesas.Nome into g
                        select new
                        {
                            TipoDespesas = g.Key,
                            valores = g.Sum(d => d.Valor)
                        };


            return Json(query);
        }

        public JsonResult GastosTotais()
        {
            var query = _context.despesas.
                OrderBy(m => m.Meses.MesId).
                GroupBy(m => m.Meses.MesId).
                Select(d => new { NomeMeses = d.Select(x => x.Meses.Nome).
                Distinct(), Valores = d.Sum(x => x.Valor) });
            return Json(query);
        }
    }
}

GerenciadorDespecas/ViewComponents/EstatisticaViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GerenciadorDespecas.Models;
using GerenciadorDespecas.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDespecas.ViewComponents
{
    public class EstatisticaViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        public EstatisticaViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            EstatisticaViewModel estatistica = new EstatisticaViewModel();
            estatistica.MenorDespesa = _contexto.despesas.Min(x => x.Valor);
            estatistica.MaiorDespesa = _contexto.despesas.Max(x => x.Valor);
            estatistica.QuantidadeDespesas = _contexto.despesas.Count();
            return View(estatistica);

        }
    } 
}

GerenciadorDespecas/Views/Despesas/Create.cshtml
@model GerenciadorDespecas.Models.Despesas

@{
    ViewData["Title"] = "Nova Despesas";
}


<div class="formulario">
    <h6>Despesas</h6>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" class="form rounded border">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="MesId" class="control-label">Mês</label>
                    <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TipoDespesaId" class="control-label">Tipo de Despesa</label>
                    <div class="input-group">
                        <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                        <div class="input-group-append">
                            <button type="button" class="btn  btn-outline-info" data-toggle="tooltip" data-placement="right" title="Adicionar novo tipo de despesas " onclick="MostrarModal()">
                                <i class="far fa-plus-square"></i>
                            </button>

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-primary btn-sm" />&nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Modal despesas-->
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Adicionar nova despesa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input class="form-control txtDespesa"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnAdicionar">Adicionar</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        function MostrarModal() {
            $(".modal").modal();


            $(".btnAdicionar").on('click', function () {
                var txtDespesa = $(".txtDespesa").val();


                $.ajax({
                    url: "/TipoDespesas/AdicionarTipoDespesa",
                    method: "POST",
                    data: { txtDespesa: txtDespesa },
                    success: function (data) {
                        if (!data) {
                            $(".modal").modal('hide');
                            $(".modal").modal('dispose');
                            $('.btnAdicionar').unbind('click');
                            $('.txtDespesa').val('');
                            alert("Tipo de despesa ja cadastrado");
                        }
                        else location.reload(true);
                    }
                })
            });
        }
    </script>


}

GerenciadorDespecas/Views/Despesas/Edit.cshtml
@model GerenciadorDespecas.Models.Despesas

@{
    ViewData["Title"] = "Edit";
}

<div class="formulario">

    <h6>Despesas</h6>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" class="form rounded border">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DespesaId" />
                <div class="form-group">
                    <label asp-for="MesId" class="control-label">Mês</label>
                    <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                    <span asp-validation-for="MesId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TipoDespesaId" class="control-label">Tipo de Despesa</label>
                    <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                    <span asp-validation-for="TipoDespesaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-primary btn-sm" />
                    <a asp-action="Index" class="btn btn-outline-primary btn-sm" >Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorDespecas/Views/Despesas/Index.cshtml
@model X.PagedList.IPagedList<GerenciadorDespecas.Models.Despesas>
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Common
@{
    ViewData["Title"] = "Cadastro de despesas";
}

<div class="tabela">
    <div class="container">
        <p class="btnNovo">
            <a asp-action="Create" class="btn btn-outline-primary btn-sm">Cadastro de despesas</a>
        </p>

        @if (TempData["Confirmacao"] != null)
        {
            <h6 class="alert alert-success">@TempData["Confirmacao"]</h6>
        }

        <div class="row justify-content-md-center">
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"><strong>Mês</strong></label>
                <div class="col-sm-9">
                    <select class="form-control escolhaMes" asp-items="ViewBag.Meses"></select>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col">
                <partial name="_GastoTotalMes" />
            </div>
            <div class="col">
                <partial name="_GastoMes" />
            </div>
        </div>



        <div class="row">
            <div class="col">
                <partial name="_GastosTotais" />
            </div>
        </div>


        <div class="estatisticas">
            <div class="alert alert-primary">
                @await Component.InvokeAsync("Estatistica")
            </div>
        </div>

        <div class="tabelaPrincipal">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            Meses
                        </th>
                        <th>
                            Tipo da Despesa
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Ação
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Meses.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Valor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoDespesas.Nome)
                            </td>
                            <td>
                                <a class="btn btn-outline-primary btn-sm" asp-action="Edit" asp-route-id="@item.DespesaId">Editar</a>
                                <a class="btn btn-outline-danger btn-sm" onclick="ExibirModal(@item.DespesaId)">Excluir</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.PagedListPager(Model, pagina => Url.Action("Index", "Despesas", new { pagina}), new PagedListRenderOptionsBase
{
    LiElementClasses = new string[] {"page-item"},
    PageClasses = new string[] { "page-link"}
})

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir essa despesas ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{

<script src="~/bundle.js"></script>
    <script>

        CarregarDadosGastoMes();
        CarregarDadosGastosTotaisMes();
        CarregarDadosGastoTotais();

        function ExibirModal(id) {
            // $(".nome")[0].innerHTML = nome;
            $(".modal").modal();
            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "Despesas/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>
}